### ISSUE TITLE
Display all relevant error messages - investigation

### ISSUE THREAD

**Issue by chrisruk** [RaspberryPiFoundation/editor-ui#341]

**Comment by maddyjoe** [comment]
Issues uncovered (probably badly-worded but just for historical reference of the issues uncovered/resolved):
1. Skulpt/run was completing before all errors had time to be discovered (e.g. where draw function looping was used) and hence output
2. some errors weren't persisting if run--> output, not corrected and then run again due to cache clear (see screenshot)
3. in the friendly error messages, built to just output in javascript some errors not being passed as we have a third layer on top in our implementation

![image](https://user-images.githubusercontent.com/66950158/214311256-fbf922fa-6f78-48dc-b611-6a741ff19742.png)
