### ISSUE TITLE
HTML/CSS v1 - External release

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#493]
Part of https://github.com/RaspberryPiFoundation/digital-editor/issues/94 and a follow on from https://github.com/RaspberryPiFoundation/editor-ui/issues/462

Aspects that go beyond simply replacing trinket (https://github.com/RaspberryPiFoundation/editor-ui/issues/462) but enhance the experience for HTML/CSS users.

This includes:
- Selecting programming language:
  - Landing page for signed out (#531)
  - Modal for logged in (#505)
- Fixing the resize panel bug where resizing the screen after adjusting panels can cause the panels to go off screen. Panel split to resize proportionally.
- Output topbar (#504 & #498)

Feature branch: [html-css-v1](https://github.com/RaspberryPiFoundation/editor-ui/tree/html-css-v1)

**Comment by maxelkins** [comment]
# Landing page comments:

- Button Icons need to be exported with the internal 'white space'' included, aka the buttons should be 1:1 svgs when exported. They can be exported [here](https://www.figma.com/file/k8HLf9t06G8QtlMzQlgHGk/RPF-Design-System---Component-Library?type=design&node-id=1781-13797&mode=design&t=v5080XsTHRKczIJZ-4)
- The buttons are misaligned vertically
- Button style
  - The button height is too large see spec [here](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=942-8848&mode=design&t=2cFBbgKY1uTrAGjb-4)
  - Button as a whole may be one to pick up with the button ticket.
- With the link button - should the link be inside a button?
  - Maybe we should do it like the project site one so its just a link styled as a button - [storybook](https://projects.raspberrypi.org/design-system/?path=%2Fstory%2Fbutton--link-button&globals=locale%3Aen)
  - Current implementation has focusing issues as the keyboard focuses the button (which doesn't do anything when actioned) before the link. This is also an issue with mouse interaction as you have to exactly click the text rather than the button as a whole.
- The footer seems to be a tad broken visually on dark mode. Maybe it should just have the same background colour as the page.
