### ISSUE TITLE
Spike: Access parent redux store from web component

### ISSUE THREAD

**Issue by PetarSimonovic** [RaspberryPiFoundation/editor-ui#689]

**Comment by loiswells97** [comment]
### Findings

- We can't pass a function as an attribute to the web component. This is because it is a custom HTML element, and all HTML attributes must be strings. Whilst you could convert the function to a string and back again, it is considered poor practice from a security perspective.
- There is the possibility of adding a property to the web component containing the required callback, but this would require JavaScript fiddling in the host application - do we really want to go down this route?

**Comment by sra405** [comment]
great spike and findings 👍 will help for tickets this sprint
