### ISSUE TITLE
Login to the host app from web-component

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#745]
We need the functionality to trigger login and signup via the host application from the web component (i.e. in the [new downloads sidebar panel](https://www.figma.com/file/SrINjD1MCT6VWYf1Yc9fV1/Code-Editor---Designs?type=design&node-id=3734-69935&mode=design&t=2gODKub9tIgfQkt1-4)).

Initial thinking:
- fire off login or signup custom events from the web component
- pick these events up by the host
- trigger the hosts typical login/signup flow

**Comment by PetarSimonovic** [comment]
- [ ] Users can log in or sign up to the projects site using these buttons~ (https://github.com/RaspberryPiFoundation/editor-ui/issues/745)
  - [ ] They are then also logged into to Editor 
  - [ ] When logged in, their progress within the Project and their accompanying Editor code is saved, so that they can return to it

**Comment by PetarSimonovic** [comment]
Ticket [#740](https://github.com/RaspberryPiFoundation/editor-ui/issues/740) offers further context on the log in, sign up and download functionality
