### ISSUE TITLE
Web component save button on mobile

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#783]
What to do about the save CTA for the web component when integrated into the project site?

**Comment by maxelkins** [comment]
## Current issue

In the intergration, in mobile layout, as we hide the projectbar and home tab (with the log in / save button), there is/was the user would have to know to open the sidebar > download option and log in.

This doesnt feel obvious enough due to it not showing on page load and requiring the user to think 'saving' would be in download.

## Partially solved?

We now have different states for the save button in the project bar.
- Not logged in, Button = Log in to save
- Logged in, No button, shows save status.
- Logged in but not 'remixed, Button = Save.

We also auto save the project when the user is logged in, stanalone and projects site.

However how do we handled logged out users? We are still requiring them to go to the sidebar.

## Ideas

- Change the text on the log in button in the side bar to match what the projectbar says when the user is logged out - "Log in to save. And also remove the sign up button. At least this was it is clearer that you need to log in to save, although we do say this in the copy above.
- Change the download tab to something else - maybe back to the 'Home' tab? but we should still default to the instructions.
- Also update the copy in the toast notification telling you to save - do we show this on the project site/is this in the web component?
- Rethink hiding the ProjectBar on mobile - in call cases.

**Comment by maxelkins** [comment]
# To do

- [ ] Update Download panel icon to the Save icon
- [ ] Update Download panel title to "Save & Download"
- [ ] Update Log in button text to "Log in to save" in Download panel
- [ ] Update sub-copy in Download panel to:
    - "With a Raspberry Pi Account you can save your code and project steps progress."

[Figma](https://www.figma.com/file/Rbn27JvH8A8wwqagKSReIq/Code-Editor---Component-library?type=design&node-id=1144-10197&mode=design)

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/80a11775-10ae-43b1-9cde-c9d3e7245517)
