### ISSUE TITLE
Productionise dynamic pyodide runner

### ISSUE THREAD

**Issue by sra405** [RaspberryPiFoundation/editor-ui#979]
> ## Productionisation
> 
> - [x] Possibly refactor the regex for the imports to make it less of an eyesore/work better
> - [x] Add messaging to explain why you can't use certain libraries together
> - [x] Test that existing non-`p5` projects still work in `pyodide`
> - [x] Check the accessibility of hiding the runners with CSS rather than javascript
> - [x] Fix the tests
> - [x] Add new tests for the switching functionality between `pyodide` and `skulpt`
>  

 _Originally posted by @loiswells97 in [#936](https://github.com/RaspberryPiFoundation/editor-ui/issues/936#issuecomment-1988295751)_

closed by #937

**Comment by loiswells97** [comment]
### Explaining why certain modules are incompatible

It would be helpful to explain to users why they cannot use certain modules together that they are able to use separately. This scenario will arise when they try to use a `pyodide`-only module in combination with a `skulpt`-only module, and will lead to the user receiving the `skulpt` error message `ImportError: No module named {module} on line {line_number} of {file name}`. We can intercept this error message, extract the name of the problematic module and then rewrite the error message or add an explanation onto the end, e.g. `ImportError: No module named numpy on line 2 of main.py. This may be because numpy cannot currently be used with p5 or sense_hat.` However, this could be confusing for users in the case where they receive this error message for reasons other than because the modules are incompatible, for example, if they have misspelt the name of the import (which could be an external module, or another file from within the project).

**Comment by MFarringtonRPF** [comment]
Libraries that won't work: p5, py5, py5imported and sense_hat

In discussion with Max & Lois, we think:
- We should display the original error message, then say something like "Check your code for any typos. This error might also be caused if you have already used the p5, py5, py5imported or sense_hat libraries in your code. The library you are trying to import might not be compatible with those libraries."
- OR "See this [incompatibility note](open page or modal? with the explanation) for more details."
- We should try to include the list of libraries that won't work to start with, either in the message or in a modal, then have a page later (via user support area) that shows libraries in more detail for teachers especially.

**Comment by loiswells97** [comment]
I made the message a little more succinct and added scroll if it overflows vertically, and this is what it looks like:

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/88904316/7fcd8e99-5fbf-44ef-8d8b-aae1aac7c794)

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/88904316/a5be0b6b-9a28-471d-a9c8-9fe086f3d652)

**Comment by MFarringtonRPF** [comment]
@loiswells97, final copy (also CE'd):

> ImportError: No module name X on line 3 of main.py. You should check your code for typos. If you are using p5, py5 or sense_hat, X might not work.

**Comment by sra405** [comment]
work merged into feature branch
